from bionumpy.encodings.string_encodings import StringEncoding

atom_values = ['C',
               'CA',
               'CB',
               'CD',
               'CD1',
               'CD2',
               'CE',
               'CE1',
               'CE2',
               'CE3',
               'CG',
               'CG1',
               'CG2',
               'CH2',
               'CZ',
               'CZ2',
               'CZ3',
               'N',
               'ND1',
               'ND2',
               'NE',
               'NE1',
               'NE2',
               'NH1',
               'NH2',
               'NZ',
               'O',
               'OD1',
               'OD2',
               'OE1',
               'OE2',
               'OG',
               'OG1',
               'OH',
               'OXT',
               'SD',
               'SG']
AtomEncoding = StringEncoding(atom_values)


residue_values = ['ALA',
 'ARG',
 'ASN',
 'ASP',
 'CYS',
 'GLN',
 'GLU',
 'GLY',
 'HIS',
 'ILE',
 'LEU',
 'LYS',
 'MET',
 'PHE',
 'PRO',
 'SER',
 'THR',
 'TRP',
 'TYR',
 'VAL']
ResidueEncoding = StringEncoding(residue_values)
